### ISSUE TITLE
Suggestion: in the places where the unlocks are.....

### ISSUE THREAD

**Issue by mgracer48** [Slimmmo/Slimmmo.github.io#102]
There should be buttons for adding 10,100,and 1000 for each one
Same for subtracting

**Comment by mgracer48** [comment]
Yes

**Comment by ricardopetrere** [comment]
Well... There's a PR, #87, related to the same suggestion as yours.
I made a working example on [http://ricardopetrere.github.io/Slimmmo.github.io/](http://ricardopetrere.github.io/Slimmmo.github.io/), see if that's what you wanted.
