### ISSUE TITLE
A way to import save file on windows mac and linux

### ISSUE THREAD

**Issue by mgracer48** [Slimmmo/Slimmmo.github.io#104]
Another thing that be cool (goes along with my accessing ios app idea) would be to load the save file on your computer that puts in all the info for all planets
And it can automatically update every minute or so

**Comment by mgracer48** [comment]
Or you can update it manually by doing something like import recent file

**Comment by 61352151511** [comment]
There's a non-auto updating one on the development version of the site. Likely there will never be an auto-updating one. I understand that it would be nice for the calculator to be as automatic as possible, but it's really not that difficult to input all your information once, and then see the recommendation, then do what it says on the calculator in game, and then click "Apply Recommendation" to see the next step.
