### ISSUE TITLE
offline app?

### ISSUE THREAD

**Issue by mgracer48** [Slimmmo/Slimmmo.github.io#105]
It be cool to have an offline version so u can do calculations on the go
without internet
i mean this all run by scripts right?
is there some way to convert this into an app for iOS and android

**Comment by denilsonsa** [comment]
Related reading (not sure how complicated it is): https://developers.google.com/web/fundamentals/getting-started/codelabs/offline/

Found through https://developer.chrome.com/apps/migration

**Comment by Slimmmo** [comment]
I agree an app would be cool but it's unlikely to happen, sorry. All the calculations are done in the Javascript though so if you can download the page it will work offline.

**Comment by NicholasRBowers** [comment]
Hmm, don't think it's necessary to build anything in from this side for this.  You've really got two options:

1. Clone the project on your machine and open `index.html` in the browser.
2. Enable [offline browsing](http://www.howtogeek.com/263577/how-to-enable-offline-browsing-in-chrome/) in Chrome.

Option 2 should be sufficient for things like Chromebooks, so I don't think that there is anything else to be done here.

**Comment by 61352151511** [comment]
Yea, I think downloading the page for offline viewing should be sufficient so I'll close this issue. Feel free to take up the task on your own though.
