### ISSUE TITLE
Is 17.77x supposed to be permanently checked in the "Gold/Platinum Upgrades + Suits" accordion?

### ISSUE THREAD

**Issue by NicholasRBowers** [Slimmmo/Slimmmo.github.io#111]
This comes checked by default for me, and I cannot uncheck it.

<img width="560" alt="screen shot 2016-09-22 at 11 31 27 am" src="https://cloud.githubusercontent.com/assets/1668224/18754861/23ea7d6c-80b8-11e6-944e-1db836cd970b.png">

**Comment by 61352151511** [comment]
Yes, the Platinum boost occurs when all investments are gold boosted the default is 17.77, this isn't applied on the calculator unless you have mega boost checked for all investments

**Comment by NicholasRBowers** [comment]
Cool.
