### ISSUE TITLE
Earth manager costs should not be mutually exclusive

### ISSUE THREAD

**Issue by inverseparadox** [Slimmmo/Slimmmo.github.io#12]
On Earth, when I select the 99.999%-cost-reduction manager for a given investment, the calculator automatically deselects the 10%-cost-reduction manager for that investment. (The reverse is also true.)

However, I've noticed that after this, the listed cost for the next level of that investment is inaccurate. For example, I currently have Donut Shops at 2,999, with both managers, and the calculator lists the cost of upgrading it to 3,000 as 666.59 trequadragintillion - but the game itself lists the cost of upgrading to 3,000 as 599.931 trequadragintillion. This is exactly 10% less than the figure listed by the calculator.

As a result, the calculated time till the next upgrade is inaccurate, and presumably the calculated upgrade scores (which are based on minimizing those times) can be as well.

Please make it possible to select both types of managers at once, with the cost-reduction percentages multiplying appropriately.

**Comment by Slimmmo** [comment]
If you close and re-open the game what happens to the price? I'm just wondering if this is the stacking manager bug or if they have changed the game.

**Comment by inverseparadox** [comment]
I just noted down the price of upgrading Shrimp Boats (and verified that it was 90% of the price shown in the calculator, to within rounding error - 89.98%), exited the game, reopened it, and checked again. The price had not changed.

If there is a specific test you'd like me to carry out, please let me know.

**Comment by Slimmmo** [comment]
Previously if you bought the 99.999% manager and then the 10% manager, then you would lose the discount of the 99.999% manager. Since it appears this is no longer the case, I've added support for buying both at the same time. Enjoy.

**Comment by inverseparadox** [comment]
I haven't specifically tested buying the 99.999% manager and then the 10% manager; I always get the 10% manager first, since I can't afford the 99.999% one until much later. So technically I can't confirm that doing things in the order you describe doesn't still have that effect, but I can confirm that doing it in the other order doesn't seem to produce the equivalent result.

Thanks for the fix!

**Comment by inverseparadox** [comment]
I'm not sure whether this should be reopened or whether I should file a new issue, but the fix doesn't seem to have worked.

If I select the 99.999% discount for Lemons and hit Calculate, the displayed cost for +1 Lemons changes appropriately - but if I then also select the 10% discount and hit Calculate, the displayed cost does not change. It still remains 10% above what the game shows. (However, selecting the 10% discount alone does produce the expected change vs. having neither discount selected.)

If there should be a separate issue for that, please let me know and I can file one with an appropriate description.

**Comment by Slimmmo** [comment]
Sorry should be fixed now.
