### ISSUE TITLE
Cost of Upgrades on "Black & Blue Friday" event is incorrect.

### ISSUE THREAD

**Issue by enki1337** [Slimmmo/Slimmmo.github.io#137]
The "$ Cost +1" column of the "Cost of Upgrades" chart is higher than expected by one upgrade for all items. This messes up all the recommendations, as Cash Upgrades are viewed as relatively less exensive than they should be.

I'm not sure if this is only a "Black & Blue Friday" event problem, or if other events are affected as well, but it does not seem to affect Earth.

Edit: I just reset the event, and the problem is there right from the start. Also, the starting number of each item is 0 in the calculator instead of the 1 you get in the actual game.

**Comment by Slimmmo** [comment]
I've updated to hopefully fixed but I haven't checked it personally so let me know please.

**Comment by enki1337** [comment]
Seems to work fine now.

Also, wow, that was super quick!  Thank you for making this great tool! <3

**Comment by Slimmmo** [comment]
Thanks, you're welcome :)
