### ISSUE TITLE
Mars Men Unlocks at 500 & 1000 for Speed Incorrect

### ISSUE THREAD

**Issue by ooglek** [Slimmmo/Slimmmo.github.io#140]
According to the Unlocks Gallery:

- 500 Men -- Speed of Men profits x5
- 1000 Men -- Speed of Men profits x5

I've got 2450 Men, with my 2x video bonus, at 117.811 quindecillion per cycle. According to my spreadsheet, that 25x speed multiplier would drop the time on Men to 0.01125 seconds per cycle, or 10.5E+51 (sexdecillion) per second. 

The rate per second shown on the site is $1.675 Sexdecillion, which represents a 4x ( 2 * 2 ) speed up.

The rate per second, I believe, should be $10.5 Sexdecillion, which represents a 25x ( 5 * 5 ) speed up.

`25 / 4 = 6.25` and `6.25 * 1.675 = 10.46875`

I suspect this line needs changing:

https://github.com/Slimmmo/Slimmmo.github.io/blob/14debf4831a14b77fdaf076904dda3b78b47acde/js/main.js#L2126

Instead of `[500, [5, 2]]` and `[1000, [5, 2]]` it should be `[500, [5, 5]]` and `[1000, [5, 5]]` though I haven't looked at the code super closely. :-)

**Comment by Slimmmo** [comment]
I've pushed the change to the live site. Let me know how it looks.

**Comment by Nutty69** [comment]
Seems good to me.

I have 13,300 Men @ 87.774 novemoctogintillion per cycle
That's would be ~9.7527... novemoctogintillion per second without any speed boosts

Speed boosts acquired are 500 Men (x5), 100 Men (x5), and all 18 of the "of everything" (x2^18).
Total speed increase is x6,553,600

That brings it to ~63915295 novemoctogintillion per second
Which is about 63.915 unnonagintillion per second
Calculator shows 63.916 unnonagintillion per second
