### ISSUE TITLE
Why are Super Badges listed in the order they are?

### ISSUE THREAD

**Issue by Nutty69** [Slimmmo/Slimmmo.github.io#146]
Are Super Badges in the calculator listed in any particular order?

The Super Badges I have available in game are not listed in the same order as the calculator (playing Steam on Windows). The order in my game is: Cupid, Silver Blade, Fuzzee, Turdy, Pro-Team Shake, Cereal, Haunted Mansion, MXC, Budget Light -- which are number 17, 9, 15, 27, 16, 23, 25, 22, and Budget Light isn't listed.

I'm guessing the order they show up in one's game is based on the order one completes the events.

Would there be any benefit to ordering the Super Badge list either alphabetically or by investment by planet?

**Comment by 61352151511** [comment]
The order in the calculator is the order that they have been added to the game. And yes, the order they display to the user is the order in which they earned the badges. There is no real benefit to changing how it's displayed on the calculator other than having the badges be easier to find.
