### ISSUE TITLE
Typo in Profit-A-Bowl investment

### ISSUE THREAD

**Issue by Nutty69** [Slimmmo/Slimmmo.github.io#148]
"Foam Stiff-arms" are incorrectly titled "Foam Sitff-arms". I created Pull Request #147 to correct the issue.

**Comment by 61352151511** [comment]
Hi, as I previously read you're new to github I'll be forgiving. The managers (optionally) get an email anytime an issue/pull request is created or commented on. Creating a pull request to fix an issue is basically the same thing as creating an issue. There's no need to create an issue just to tell us that you made a pull request to fix it.
I'm going to leave the pull request a little but just in case you spot more small issues that you'd like fixed.

**Comment by Nutty69** [comment]
Apologies, and thanks.
