### ISSUE TITLE
handling of x3 multipliers is wrong

### ISSUE THREAD

**Issue by cwitty** [Slimmmo/Slimmmo.github.io#15]
I'm playing Adventure Capitalist on Android.  I bought two x3 upgrades (so the game says "x6"), and I usually have the x2 multiplier from watching an ad.  When I put these into the calculator with a 2 under "Gold multipliers" and a 2 in "x multiplier" under "other bonuses", the calculator gives numbers that are too high; I can get the correct numbers by returning "Gold multipliers" to 0 and setting "x multiplier" to 8.

So I think what the game is doing is considering each 3x multiplier to be +300%, and (inconsistently) considering the 2x multiplier to be +100%; but instead of multiplying them like your calculator does: (1 + 2 * 300%) * (1 + 100%) = 14
the game actually adds them:
(1 + 2 * 300% + 100%) = 8

**Comment by Slimmmo** [comment]
Thanks for pointing this out. This is a simple thing to fix so I'll do it soon.

**Comment by Slimmmo** [comment]
This should be fixed so I'm closing this. If it's not fixed feel free to re-open.
