### ISSUE TITLE
Missing cash upgrades for Black & Blue Friday (Replay)

### ISSUE THREAD

**Issue by seraku24** [Slimmmo/Slimmmo.github.io#154]
It appears the Black & Blue Friday event has changed for the current replay, and there are many more cash upgrades than the calculator shows.

The current version of the calculator stops at **All Profit 24** ($100 Vigintillion).  Through my current progress in the event, I can see the following:

|Name|Reward|Cost|
|---|---|---|
|First In Line|All profits x25|$1 sexvigintillion|
|Paint it, Black and Blue|All profits x26|$1 septenvigintillion|
|Black and Blue Magic|All profits x27|$1 octovigintillion|
|99.99% Off!|All profits x28|$1 novemvigintillion|
|Free Therapy for Retail Workers|All profits x29|$1 trigintillion|
|Ample Parking for Everyone|All profits x30|$1 untrigintillion|
|Reinforced Door Hinges|All profits x31|$1 duotrigintillion|
|Water Cannons|All profits x32|$1 tretrigintillion|
|Open 24 Hours|All profits x33|$1 quattuortrigintillion|
|Customer Brawl Referees|All profits x34|$1 quintrigintillion|

**Comment by seraku24** [comment]
And I see that @Nutty69 has a pending PR (#153) that would address this once verified and accepted.

**Comment by Nutty69** [comment]
I managed to purchase the x25 multiplier and the list of available upgrades still ends at x34 (i.e. purchasing the x25 did not reveal anything beyond the x34) so I believe the list is complete. I *think* PR #153 is correctly coded. If so, maybe @Slimmmo will approve it.

**Comment by Slimmmo** [comment]
Merged, sorry it took too long.
