### ISSUE TITLE
Incorrect unlocks in Excellent AdVenture (Replay)

### ISSUE THREAD

**Issue by seraku24** [Slimmmo/Slimmmo.github.io#157]
The current replay of The Excellent AdVenture has slightly different unlocks.  All businesses should have their first unlock at five (5), whereas the calculator lists Bubonic Mouse Traps and Pirate Ship Outboard at four (4) and three (3), respectively.

**Comment by Nutty69** [comment]
I've created PR #158 that includes those changes as well as adding "MegaTickets" (called "Gilding" in the event).

**Comment by Slimmmo** [comment]
Merged, look good?

**Comment by seraku24** [comment]
Sorry for the delay.  Closing this as it was all good.
