### ISSUE TITLE
Replay of Root of All Evil has changed.

### ISSUE THREAD

**Issue by seraku24** [Slimmmo/Slimmmo.github.io#168]
It seems that Hyper Hippo are continuing to tweak events when replayed.

**Edit:** _**Everything is different.**_  The costs of businesses, the profits generated, and the unlocks are also all incorrect.  (Time to just play this by hand, since the calculator has been made useless.)

~~This time, though, the entire upgrade tree seems different. I have only just started so I cannot see the entire list, but here are the ones I can see:~~

**Edit 2:** Removed items already in the PR.

|Angel Upgrade|Cost|
|---|---|
|...|...|
|~~+66 Rope Slinger~~|~~77 quadrillion AI~~|
|+44 Samurai Pizza Turtles|77 quadrillion AI|
|+33 BadDay|77 quadrillion AI|
|+22 Mag-Neato|77 quadrillion AI|
|+11 The Prankster|77 quadrillion AI|
|+6 Jareth Green|77 quadrillion AI|
|+2 Hair Clan|77 quadrillion AI|
|SuperKing profit x7|77 quadrillion AI|
|Honey Badger profit x7|777 quadrillion AI|
|Black Knight profit x7|7 quintillion AI|
|Rope Slinger profit x7|77 quintillion AI|
|Samurai Pizza Turtles profit x7|777 quintillion AI|
|BadDay profit x7|7 sextillion AI|
|Mag-Neato profit x7|77 sextillion AI|
|The Prankster profit x7|777 sextillion AI|
|Jareth Green profit x7|7 septillion AI|
|Hair Clan profit x7|77 septillion AI|
|All profits x7|7 octillion AI|
|-End-|-End-|

|Cash Upgrade|Cost|
|---|---|
|...|...|
|~~Hair Clan profit x6~~|~~$10 decillion~~|
|All profits x9|$666.666 decillion|
|SuperKing profit x6|$1 undecillion|
|Honey Badger profit x6|$2 undecillion|
|Black Knight profit x6|$3 undecillion|
|Rope Slinger profit x6|$4 undecillion|
|Samurai Pizza Turtles profit x6|$5 undecillion|
|BadDay profit x6|$6 undecillion|
|Mag-Neato profit x6|$7 undecillion|
|The Prankster profit x6|$8 undecillion|
|Jareth Green profit x6|$9 undecillion|
|Hair Clan profit x6|$10 undecillion|
|All profits x9|$100 undecillion|
|SuperKing profit x6<br>"No Mercy!"|$3.33 duodecillion|
|Honey Badger profit x6<br>"Beast of Durden"|$6.66 duodecillion|
|Black Knight profit x6<br>"Body Armor Nipples"|$9.99 duodecillion|
|Rope Slinger profit x6<br>"Wild Wild Web"|$24 duodecillion|
|Samurai Pizza Turtles profit x6<br>"The Goon Gala"|$48 duodecillion|
|BadDay profit x6<br>"What a Hackman"|$64 duodecillion|
|Mag-Neato profit x6<br>"Custom Baby Seal Pumps"|$128 duodecillion|
|The Prankster profit x6<br>"You're A Gas"|$200 duodecillion|
|Jareth Green profit x6<br>"Wasn't Osborn Yesterday"|$355 duodecillion|
|Hair Clan profit x6<br>"Swiss Army Ninja"|$500 duodecillion|
|All profits x9<br>"The Just Us League"|$1 tredecillion|
|SuperKing profit x66<br>"It's Now or Later"|$6.666 quattordecillion|
|Honey Badger profit x66<br>"Lean, Mean, Jean Lovin' Machine"|$66.666 quattordecillion|
|Black Knight profit x66<br>"What's in a Utility Belt"|$666.666 quattordecillion|
|Rope Slinger profit x66<br>"Upside Down Smoochies"|$6.666 quindecillion|
|Samurai Pizza Turtles profit x66<br>"Secret of the Mews"|$66.666 quindecillion|
|BadDay profit x66<br>"Krypto-Currency"|$666.666 quindecillion|
|Mag-Neato profit x66<br>"Mega Minion"|$6.666 sexdecillion|
|The Prankster profit x66<br>"Want To See A Magic Trick?"|$66.666 sexdecillion|
|Jareth Green profit x66<br>"Tiny Gold Flakes"|$666.666 sexdecillion|
|Hair Clan profit x66<br>"Shredder-ed Wheat"|$6.666 septendecillion|
|All profits x9<br>"It's a Bird!"|$66.666 septendecillion|
|-End-|-End-|

**Comment by Nutty69** [comment]
That's about as far as I can see as well. I've created PR #169 to update the Cash and Angel Upgrades as far into the lists as I can see right now (8.8 septillion cash; +66 Rope Slingers from Angels). When I can see farther into the list, I'll post another update (I'm guessing some time tomorrow I'll have enough AI to reset.)

**Comment by seraku24** [comment]
@Nutty69 I see that your PR was merged.  Just so you know, there are still more upgrades.  I will keep updating the original table as I make progress.

**Comment by seraku24** [comment]
@Nutty69 Sorry about that.  I forgot to remove the other question mark when I put in +11.  And there is what looks like another set of cash upgrades too, starting at $3.33 duodecillion.

**Comment by Nutty69** [comment]
Created PR #170 with updates through 100 undecillion and +11 The Prankster.

I'm still sitting on ~500,000 investors and ~$8 sextillion and I can't see anywhere near that far into the upgrades lists :-(

The cash upgrades starting at 3.33 duodecillion don't correspond to anything in the original version.

Since I also contribute to the Wiki, is there any chance you could add the names of the upgrades from 3.33 duodecillion onward into the list (in case I don't make it that far myself)?

**Comment by seraku24** [comment]
@Nutty69 No problem.  I'm at 67.599 billion AI, so it is slow-going to reveal the rest of the angel upgrades.

I'll include the names on the rest of the cash upgrades, and I have sketched out the next block of cash upgrades following the pattern before.

**Comment by seraku24** [comment]
@Nutty69 I just finished the cash upgrade list.  I'm at 21.977 quadrillion AI now and moving a little faster per reset.

**Comment by Nutty69** [comment]
@seraku24 I was invited by @Slimmmo to collaborate (woohoo, I feel honored). I've merged the PR that should have all the upgrades. Give it a few minutes, then reload the page and let me know if it looks good.

**Comment by seraku24** [comment]
@Nutty69 Congrats on the collaborator status! 🎊 

~~I refreshed the page, and something is wrong with the calculations.  The calculator is overestimating my income by a factor of 111.  The error is even across all businesses so I wonder if there is an issue with one or more of the "all profits".  I will reset and review the upgrades to see if I can spot it.~~  Just found it.  One of the angel upgrades says "All Profits 777" when it should just be "All Profits 7".  There were all those 7's, I probably just got number blind and typed a few too many.  Other than that, I think it is all good.

I trust that you also have enough data for the Wiki updates too?

**Comment by seraku24** [comment]
This all looks good.  Thanks!
