### ISSUE TITLE
Megabucks Updates

### ISSUE THREAD

**Issue by apleith** [Slimmmo/Slimmmo.github.io#171]
I think there was a prior issue post that somewhat mentioned this; however, I wanted to clarify the issue. Also, thank you for putting this together.

The game now has permanent profit multipliers purchased through megabucks that were previously cash upgrades. For example, the Lemon Profit 3 marked as $1 sexsexagintillion is now 70 megabucks. Here are the 8 presently on my upgrade list, though I'm barely past the midway point, so I'm certain there are probably more following these.

- Lemon Profit 3 ($1 Sexsexagintillion) is now 70 megabucks
- Carwash Profit 3 ($96 Sexsexagintillion) is now 70 megabucks
- Shrimp Profit 3 ($679 Sexsexagintillion) is now 80 megabucks
- Bank Profit 3 ($81 Septsexagintillion) is now 100 megabucks
- Angel Investor 2.1 ($1 Octosexagintillion) is now 200 megabucks
- Hockey Profit 3 ($9 Octosexagintillion) is now 110 megabucks
- Oil Profit 3 ($328 Octosexagintillion) is now 120 megabucks
- Angel Investor 1.5 ($1 Septuagintillion) is now 200 megabucks

It isn't a huge deal, really, since I am presently just ignoring those recommendations when I pull up the calculator.

Again, thanks for doing this and keeping it pretty well updated. It helps me from letting AC dominate my thoughts while working on my dissertation.

**Comment by Nutty69** [comment]
@apleith Yes, it's a known issue (#139). I've been working on a possible method of separating out the Mega Bucks Upgrades in my clone at https://nutty69.github.io/

BUT I haven't worked out saving / loading so if you mark any of the Mega Bucks Upgrades as having been bought, you'll probably need to re-check them each time you load the page. If you haven't bought Mega Bucks Upgrades, then it should work just fine for you.

Also, my clone is not up-to-date for events; you'll need to use Slimmmo's for those.

**Comment by Nutty69** [comment]
Seems to be mooted by the most recent update that makes the boosts that had cost Earth Bucks then cost Mega Bucks now cost Earth Bucks again.
