### ISSUE TITLE
Suggestion: "Profiles"

### ISSUE THREAD

**Issue by 61352151511** [Slimmmo/Slimmmo.github.io#18]
I have games running on my tablet, phone, and steam. While I could export each save file every time a change is made and try to keep track of them, another great option would be to have profiles. A drop down list choosing which profile you are currently calculating, with a New Profile and Delete Profile option. This way you could easily calculate what's best for all your games one after the other, without having to export and import a bunch of save files.

**Comment by Slimmmo** [comment]
Good suggestion. I'll implement it but don't hold your breath :smile:.

**Comment by 61352151511** [comment]
I might be able to implement this if I find some time, maybe this weekend.

**Comment by 61352151511** [comment]
Closing issue because it's on /dev
