### ISSUE TITLE
Discrepancies in Moon Purchase Costs

### ISSUE THREAD

**Issue by rmario505** [Slimmmo/Slimmmo.github.io#191]
I have noticed some discrepancies in some of the cost in the Moon midgame. 

When I was using the calculator, it suggested I buy Giant Lasers up 10 units to 360 for $1.46 Tresvigintillion.
![image](https://user-images.githubusercontent.com/43190116/53386004-74b8a100-394e-11e9-8884-11af475528cb.png)

However, my purchase price is much higher.
![image](https://user-images.githubusercontent.com/43190116/53386045-9ade4100-394e-11e9-99d9-8a3b61fc6342.png)

I have checked my bonuses, upgrades both cash and angel and everything seems right. Looking that the upgrade numbers it seems some of the numbers are on the money (sorry) and some are off, usually higher.

Here we have the calcuators upgrade numbers.
![image](https://user-images.githubusercontent.com/43190116/53386186-2eb00d00-394f-11e9-87f4-d4b908a6402a.png)

and here are the in game steam numbers as of this post. (using x10 to see changes easier)
![image](https://user-images.githubusercontent.com/43190116/53386209-4d160880-394f-11e9-9ba9-130b244672ca.png)

**Comment by mizerock** [comment]
This issue might be related somehow to the MANAGERS. The manager names for Moon are listed with the names of the items on Earth. I've been using this product for years (so helpful!) and have only recently noticed that the app has the unit price all wrong for Werewolf Colonies. That totally wrecks the suggestions for what to buy.

**Comment by Slimmmo** [comment]
Hmm I hadn't noticed that before. The manager names don't update if you switch between Earth and Mars but the checkboxes do apply to the correct selected planet. Weird.

In the original post Werewolf Colonies is correct but yours isn't? How different are the values you're seeing in the game?

**Comment by Slimmmo** [comment]
You hadn't input the Angel Upgrades you've bought. the difference in prices is exactly 20 levels worth of scaling, i.e. two +10 angel upgrades.
