### ISSUE TITLE
Insert Coins to Continue is now different

### ISSUE THREAD

**Issue by jeremyhaynes217** [Slimmmo/Slimmmo.github.io#195]
The upgrades for Insert Coins to Continue event are completely different now. Instead of all being All Profit x13.37 they're broken down by each "video game". There are probably other changes as well but it's hard to tell.

**Comment by mattias-joelson** [comment]
Well, they have started mixing what they name the event with what numbers are actually present. The current event matches the Cashella event. Just substitute the names.

**Comment by DarkPulse** [comment]
Thank goodness for this report, I just found this calculator and was extremely confused at why it didn't match up with what was presented in-game.
