### ISSUE TITLE
wrong upgrade cost for amusement parks.

### ISSUE THREAD

**Issue by kylekid2000** [Slimmmo/Slimmmo.github.io#22]
it says that for the 2461 upgrade the cost is $57.002 Unquinquagintillion but on my game it says 7.41 trequinquagintillion

**Comment by kylekid2000** [comment]
i found the issue, there is a duplicate +75 angel upgrade for the amusement park

**Comment by Slimmmo** [comment]
Thanks, this should be fixed now.
