### ISSUE TITLE
Angel investor calculation for w/o sacrificed is wrong

### ISSUE THREAD

**Issue by zbecker** [Slimmmo/Slimmmo.github.io#28]
```
"moon": {
  "levels": {
    "Moon Shoe": 4857,
    "Gravity Booth": 1273,
    "Payday Clone": 3410,
    "Moon Express": 1375,
    "Oxygen Bar": 2676,
    "Helium-3 Farm": 1633,
    "Cheese Mine": 1794,
    "Amusement Park": 1451,
    "Werewolf Colony": 2058,
    "Giant Laser": 571
  },
  "numAngels": 1.24704e+50,
  "upgradeIndexUpTo": 156,
  "upgradeIndexBonus": [
  ],
  "angelUpgradeIndexUpTo": 76,
  "angelUpgradeIndexBonus": [
  ],
  "managersBought": [
    0,
    2,
    4,
    6,
    8,
    10,
    12,
    14,
    16,
    18
  ], 
  "noSingles": false,
  "noTens": false,
  "triples": 1,
  "flux": 0,
  "bonusAngelEffectiveness": 0,
  "bonusMultiplier": 0,
  "megaTicket": [
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9
  ]
},
```

Angel calculations:
Lifetime earnings: 16.646 Sextrigintillion
Angels Sacrificed: 548 Quindecillion

![image](https://cloud.githubusercontent.com/assets/504446/12879526/8e87fdde-ce02-11e5-9ced-140926da6809.png)

The values and screenshot come from a brand new reset. It's improbable for the doubled w/o to be at 0 right after a reset. Based on the image, you can see the double without sacrificed isn't calculating properly. I think what's happening is that the calculator isn't taking the sacrificed angels into consideration. 

Doubled w/o sacrificed should be 2 * (current angels) + sacrificed

Currently, Doubled w/o sacrificed is calculating as simply 2 * (current angels), which isn't accurate.

In my case, my total angels for doubled w/o sacrificed should be 797.408 quindecillion, which would equate to 28.260 sextrigintillion lifetime earnings rather than the displayed 2.285 sextrigintillion, which only covers doubling without taking into consideration my already sacrificed angels.

It's late and I might be a bit drunk from all the Super Bowl mayhem, so let me know if any of this is nonsense. Once I've sobered up tomorrow, I'll look through the code and see if I can't help identify the issue further.

**Comment by Slimmmo** [comment]
Sorry for the late reply. You're right and I've implemented a fix.

Feel free to re-open this if there's something wrong with my fix.

Thanks!
