### ISSUE TITLE
Suggestion: Display time to restart

### ISSUE THREAD

**Issue by kazerniel** [Slimmmo/Slimmmo.github.io#30]
It would be nice if there was some kind of display showing that with the current income when will the planet reach the standard restart point (when the total AI number is doubled).

I got to the point where often there's nothing to do on the Moon than to wait days for my Angels to accumulate, so it would be handy to know when to check the game next. It could even be a row on the Recommendation table, displayed similarly to purchases and upgrades, though I guess the app would need to know when I restarted last time. I guess it could be somehow tied to when the user clicks on Reset Planet.

(Btw just fyi it's not possible to comment on your Reddit thread any more, it's been archived.)

**Comment by Slimmmo** [comment]
There's a collapsing section called 'Angel Calculations' where you have to enter your lifetime earnings and angels sacrificed but then should be able to do these calculations for you. If this is not what you wanted then let me know.

Thanks for letting me know about the reddit thread.

**Comment by jaysoncopes** [comment]
Note: Should be closed :)
