### ISSUE TITLE
Request: display which suit is most beneficial

### ISSUE THREAD

**Issue by patrickgaskill** [Slimmmo/Slimmmo.github.io#33]
I imagine this could be shown as a table with each suit and the corresponding increase in production. It could be worth showing the ratio of production increase divided by the cost in gold bars too.

**Comment by Slimmmo** [comment]
The suit calculations are coming soon™ but probably won't include the gold bar cost.

**Comment by jaysoncopes** [comment]
This should be closed- has been updated.

**Comment by Slimmmo** [comment]
Thankyou.
