### ISSUE TITLE
"Recommendation: Buy All Profit 1 Cash Upgrade."

### ISSUE THREAD

**Issue by inverseparadox** [Slimmmo/Slimmmo.github.io#36]
In the Making It Rain event, although  the 50-quintillion "Angel Investor effectiveness + 1%" cash upgrade is listed as "Angel Investor 1" in the Cash Upgrades section, it is listed in the Upgrades table (below the Recommendation: line) as "All Profit 1".

**Comment by 61352151511** [comment]
Note: This can be closed
