### ISSUE TITLE
Recommendations has completely disappeared from 'The Root of All Evil'

### ISSUE THREAD

**Issue by Hezkezl** [Slimmmo/Slimmmo.github.io#48]
Just noticed there were some updates on this github, so I refreshed http://slimmmo.github.io/ to see what they were. Now the 'Recommendation' section at the bottom of the page has completely disappeared for the new event. Earth/Moon/Mars appear to be unaffected.

**Comment by Slimmmo** [comment]
Sorry, I've fixed the issue. Thanks for letting me know.

**Comment by Hezkezl** [comment]
Thank you for fixing it so quickly! :)
