### ISSUE TITLE
Suits appearing on event tab

### ISSUE THREAD

**Issue by kazerniel** [Slimmmo/Slimmmo.github.io#49]
Suits don't apply to events in the game, so their presence and the plus sign is pointless on that tab.

**Comment by Slimmmo** [comment]
Can you use flux's or gold multipliers on events? Or can I remove that whole Gold Upgrades + Suits part?

**Comment by kazerniel** [comment]
I don't know, I never spent gold on events ^^;

**Comment by 61352151511** [comment]
They can be bought

**Comment by 61352151511** [comment]
Apart from the title of the accordian, this has been fixed.
