### ISSUE TITLE
Issues when importing a lower-levelled save with higher-level values currently in calculator

### ISSUE THREAD

**Issue by Nineza** [Slimmmo/Slimmmo.github.io#5]
When the calculator has a high(er?) number of cash upgrades, angel upgrades, and managers, and then you import a save file with these not selected / activated, it doesn't seem to clear the check boxes properly, and also seems to calculate the times for the upgrades to be available according to the check boxes being ticked, despite what the save file seems to indicate.

In case the specific JSON saves in question are required:
Higher level: https://gist.github.com/Nineza/5b903ad090f943c9fed0
Lower level: https://gist.github.com/Nineza/45ef3de995c0d484b7c5

**Comment by Slimmmo** [comment]
This should be fixed now. Please let me know.

**Comment by Nineza** [comment]
Seems fixed! Definitely works with the example I gave.
