### ISSUE TITLE
Calculator completely broken after last update :X

### ISSUE THREAD

**Issue by Hezkezl** [Slimmmo/Slimmmo.github.io#54]
Seeing things like this all over the http://slimmmo.github.io/ page:

`{{ref.investments[$index][0]}}`

`{{rUC[5] | time:raw}`

`{{ref.totalMoneyPerSecond | num}})`
`Total $ / minute : {{ref.totalMoneyPerSecond * 60 | number}} ({{ref.totalMoneyPerSecond * 60 | num}})`
`Total $ / hour : {{ref.totalMoneyPerSecond * 3600 | number}} ({{ref.totalMoneyPerSecond * 3600 | num}})`

Instead of the actual numbers and things. Last update borked something :)

**Comment by Slimmmo** [comment]
This should be fixed now, thanks.
