### ISSUE TITLE
Suggestion: Only show upgrades and unlocks, not +1, +10, +100

### ISSUE THREAD

**Issue by vikusz** [Slimmmo/Slimmmo.github.io#57]
I am at a stage where I really don't care about the 0.001% profit increase from buying 100 Hockey teams even though the buy cost is only zero seconds. I just like to have all my businesses exactly at unlock levels.
As I will only buy businesses in batches of 100/200/250 to achieve the next unlock, I would like to have an option to hide all +1, +10, +100 buy options in the recommendations. Showing only cash upgrades and unlocks would be perfect.
The above is meant especially for Earth but I can see it as a nice feature for all planets/events.
Thanks for you consideration.

As a side note, I believe that the "Filter recommendations" (the time and percentage settings) options are not saved. Besides, the percentage box only takes integers; floats would be nice as well, e.g. 0.1%

**Comment by ricardopetrere** [comment]
I think this issue can now be closed, right?
