### ISSUE TITLE
Wrong costs for event cash upgrades

### ISSUE THREAD

**Issue by denilsonsa** [Slimmmo/Slimmmo.github.io#61]
I see this in-game:

* 314 quintillion
* 32.5 sextillion
* 3.36 septillion
* …

The calculator shows:

* All Profit 13.37 ($3.03 Quintillion)
* All Profit 13.37 ($3.14 Sextillion)
* All Profit 13.37 ($325 Sextillion)
* All Profit 13.37 ($3.36 Octillion)
* All Profit 13.37 ($34.7 Nonillion)
* …

I haven't checked all the numbers, but it seems most/all cash upgrades are of by a factor of 10.

**Comment by 61352151511** [comment]
Fixed.
