### ISSUE TITLE
Cost rebalancing

### ISSUE THREAD

**Issue by thorn969** [Slimmmo/Slimmmo.github.io#70]
For Earth and Moon, the costs of upgrades are significantly different than those listed. It appears the developers have done some rebalancing. It does not appear to be an issue early in the game.

But at Lemon 7777, the calculator has the cost of +1 as $212.466 Quattuorseptuagintillion and the game has it as $1.912 Treseptuagintillion, for example. On the Moon, the Werewolf Colony at 4500 costs $252.833 Octosexagintillion for +1 according to the game and $46.664 Novemsexagintillion according to the calculator.

Thank you for this calculator. It is very useful!

**Comment by dr-ishmael** [comment]
The costs match up for me on both earth and moon. Double-check that the angel upgrades and managers in the calculator match what you have purchased in-game.

**Comment by thorn969** [comment]
Hmmm... it seems to be correct now....
