### ISSUE TITLE
Suggestion: showing #angels easily when loading a gamestate

### ISSUE THREAD

**Issue by ricardopetrere** [Slimmmo/Slimmmo.github.io#80]
When you load a JSON file or just load/reload the page, the #angels is not shown as "{quantity} {order of magnitude}", for example "_7.8 septillion_". It is shown as it was loaded by the code, in this example, _7800000000000000000000000_.
I made a method to show it the first way when loading a gamestate, and it's available at [http://ricardopetrere.github.io/Slimmmo.github.io/](http://ricardopetrere.github.io/Slimmmo.github.io/).
If someone likes it, I can make the Pull Request :+1:

**Comment by vikusz** [comment]
Great idea! I was going to suggest a similar idea myself.

**Comment by ricardopetrere** [comment]
Great! Glad you liked it :)

**Comment by ricardopetrere** [comment]
Done!
