### ISSUE TITLE
(suggestion) "the wake up/aka lump sum suggestion"

### ISSUE THREAD

**Issue by vinyar** [Slimmmo/Slimmmo.github.io#91]
When you open the game after a while, your cash reserves are massive.
I would expect that in that scenario, there is a more optimal purchase that's based strictly on multipliers and not on immediate return. 

If I may make this suggestion further - perhaps a couple of rows - 1 hour, 4, 8, 24, 48, 96 simply starting count at 0$ using current values.

ah, found an example:
There is an "everything bonus". So, for example, if I have everything at 50, and oil company at 1. Upgrading oil company from 1 to 25 not only boosts its own profits & speed, but also boosts speed of all other items by 2x

ps: I love reverse engineering games like this, just got it last nigh and I'm already here looking at the code....

**Comment by Slimmmo** [comment]
Everything bonus is included in the recommendations table.

If you have a massive reserve then you can sort the table by increase in income by clicking on the header and then find the highest rated ones that you can afford.

**Comment by vinyar** [comment]
👍
